config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
  	member do
  		patch :complete
  	end
  end
  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render text: "hello, world!"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		if user_signed_in?
			@items = Item.where(:user_id => current_user.id).order("created_at DESC")
		end	
	end

	def show
	end

	def new
		@item = current_user.items.build
	end

	def create
		@item = current_user.items.build(item_params)

		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @item.update(item_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path
	end

	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path, notice: "Item successfully completed!"
	end

	private
		def item_params
			params.require(:item).permit(:title, :description)
		end

		def find_item
			@item = Item.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, label: "Item" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/items/_static_landing_page.html.erb
<div class="jumbotron">
	<h2>Welcome to your own To Do List</h2>
	<h3>Do you forget things that need to be done sometime?? If so sign up to be our member. You can track your things from here after login. Make to do list</h3>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Edit to-do-list item</h1>

	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @items.each do |item| %>
			<div class="index-wrapper">
				<% if item.completed? %>
					<div class="row item">
						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
							<p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>	
					</div>
				<% else %>	
					<div class="row item">
						<div class="col-md-8">
							<h2 class="item-title"><%= item.title %></h2>
							<p class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

		<% end %>	
	</div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>New To-Do-List Item</h1>

	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<h2><%= @item.title %></h2>
	<p><%= @item.description %></p>

	<%= link_to "Edit", edit_item_path(@item) %>
	<%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
	<%= link_to "Back", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To-Do-List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "To-Do-List", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if current_user.present? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<%= link_to "Add To-Do-List Item", new_item_path, class: "navbar-text navbar-link navbar-right" %>
			<% end %>
		</div>
	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">

  	<%= yield %>

  </div>
	
</body>
</html>